// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Identifier-0]
	_ = x[Number-1]
	_ = x[Mut-2]
	_ = x[Func-3]
	_ = x[Return-4]
	_ = x[Colon-5]
	_ = x[Comma-6]
	_ = x[Equal-7]
	_ = x[LeftParen-8]
	_ = x[RightParen-9]
	_ = x[LeftBracket-10]
	_ = x[RightBracket-11]
	_ = x[LeftCurly-12]
	_ = x[RightCurly-13]
	_ = x[DoubleColon-14]
	_ = x[NewLine-15]
	_ = x[EOF-16]
	_ = x[_tokenKindCount-17]
}

const _TokenKind_name = "IdentifierNumberMutFuncReturnColonCommaEqualLeftParenRightParenLeftBracketRightBracketLeftCurlyRightCurlyDoubleColonNewLineEOF_tokenKindCount"

var _TokenKind_index = [...]uint8{0, 10, 16, 19, 23, 29, 34, 39, 44, 53, 63, 74, 86, 95, 105, 116, 123, 126, 141}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
