// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Identifier-0]
	_ = x[Number-1]
	_ = x[Func-2]
	_ = x[Return-3]
	_ = x[Colon-4]
	_ = x[Comma-5]
	_ = x[LeftParen-6]
	_ = x[RightParen-7]
	_ = x[LeftBracket-8]
	_ = x[RightBracket-9]
	_ = x[LeftCurly-10]
	_ = x[RightCurly-11]
	_ = x[DoubleColon-12]
	_ = x[NewLine-13]
	_ = x[EOF-14]
	_ = x[_tokenKindCount-15]
}

const _TokenKind_name = "IdentifierNumberFuncReturnColonCommaLeftParenRightParenLeftBracketRightBracketLeftCurlyRightCurlyDoubleColonNewLineEOF_tokenKindCount"

var _TokenKind_index = [...]uint8{0, 10, 16, 20, 26, 31, 36, 45, 55, 66, 78, 87, 97, 108, 115, 118, 133}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
